### ISSUE TITLE
Repository-то е вратено 5 дена назад.

### ISSUE THREAD

**Issue by lencetanaskoska** [Kukunoska/LearnByPractice#10]
Избришана е базата и во Domain проектот измените од последните 5 дена се поништени.

**Comment by lencetanaskoska** [comment]
Не прајте sync од  Visual Studio-то.

**Comment by marija8888** [comment]
Не е напраено sync туку push  на делот на Кристина за DAL , но бидејќи ги немаше последните промени се врати како од пред пет дена. Мислам дека кога ќе ги превземи новите промени и публикува ќе се среди

**Comment by lencetanaskoska** [comment]
Ама ја напрајв sync и ми  се поништија сите промени, затоа и го напишав коментарот. Ако не се средит има копија од последната верзија пред DAL па ќе средиме некако.

**Comment by goce-smilevski** [comment]
Би требало да можи да се земи верзија од github заклучно со некој датум, така да ништо не е трајно изгубено, само треба да се поврзат точните верзии.

**Comment by goce-smilevski** [comment]
Во вакви терсене ситуации најдобро е еден член на тимот да го средва кодот и да го донеси во ажурна состојба, за да не си поништувате промени една со друга, работејќи паралелно на истата работа. Дали се договорифте кој ќе го прај ова ?
