### ISSUE TITLE
Својството Datum во domain класата Prijava има погрешен тип

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#14]
Си има тип DateTime кој треба да се користи за сите датуми. Со стрингот само проблеми можи да се напрат при претворање, како шо беше овај во тестот:

Test FullName:	LearnByPractice.Tests.Domain.Practice.PrijavaTest.PrijavaConstructorTest
Test Outcome:	Failed
Result Message:	
Expected string length 21 but was 19. Strings differ at index 2.
  Expected: "01-Jan-01 12:00:00 AM"
  But was:  "01.01.0001 00:00:00"
Result StackTrace:	at LearnByPractice.Tests.Domain.Practice.PrijavaTest.PrijavaConstructorTest()
PrijavaTest.cs:line 16

Ова е поради разлика во locale, македонска поддршка и слично. Кога се работи со датуми и времиња, интерно се користи соодветниот тип, во случајот DateTime.
Чарето во нашиот случај е да се смени типот на ова property во DateTime. Default вредност за овај тип треба да е 1ви Јануари 1ва година ([DateTime.MinValue](https://msdn.microsoft.com/en-us/library/system.datetime.minvalue(v=vs.110).aspx)), арно ама таја вредност не е поддржана од MS SQL Server, кај шо минималниот валиден датум е друг. Бидејќи намената на конструкторот е да постави некои почетни вредности, за пријавата е најлогично то да е тековниот **датум** ([DateTime.Today](https://msdn.microsoft.com/en-us/library/system.datetime.today(v=vs.110).aspx)).Со то и ќе се споредва во тестот.

**Comment by goce-smilevski** [comment]
И со себапот ко ќе го прилагодуваш кодот во тестот, не ќе е лошо да го забришиш Service References фолдерот од Tests проектот.

**Comment by lencetanaskoska** [comment]
поправено и забришано :D

**Comment by goce-smilevski** [comment]
Сега ќе отворам ново issue „Да не се работи во недела“.
