### ISSUE TITLE
Грешки во Database проектот

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#18]
Еве уште овие останаја од merge-от:
dbo\Tables\Predmet.sql(2,1): Error:  SQL46010: Incorrect syntax near <.
dbo\Tables\Predmet.sql(15,2): Error:  SQL46010: Incorrect syntax near ;.
dbo\Tables\Ocenka.sql(7,1): Error:  SQL46010: Incorrect syntax near <.
dbo\Tables\Ocenka.sql(13,2): Error:  SQL46010: Incorrect syntax near ;.

**Comment by Kukunoska** [comment]
Настанатите грешки во Database и TestDatabase проектот се поправени.
