### ISSUE TITLE
Зошто е класата KorisnikCollection посебна ?

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#3]
Не е наследена од Collection<T> и како шо ми изгледа, ќе има уште појќе грешки при компајлирање откако ќе се попрај претходното issue со класата Ocena.

**Comment by lencetanaskoska** [comment]
Поправено

**Comment by goce-smilevski** [comment]
Issue-во беше доделено на Андреа ...
