### ISSUE TITLE
Global assembly information

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#5]
Вредностите во AssemblyInfo.cs во Domain проектот се добри, само треба да се поделат на оние кои не зависат од проект (и тие ќе одат во глобалниот .cs file кој ќе е **надвор** од сите проекти, но фклучен во ниф како линк) и на оние кои се специфични за одреден проект (и тие ќе си останат во AssemblyInfo.cs). Примери за ова пуштиф претходно на линкот а има и практично имплементирани во Product.zip.

**Comment by andreaFIKT** [comment]
Sredeno e. Pozdrav

**Comment by goce-smilevski** [comment]
Дали проектот се компајлира во твојата развојна околина ? Кај мене не се компајлира бидејќи ProductInfo.cs и VersionInfo.cs се додаени **2 пати** (еднаш се нормално фклучени во проектот, а еднаш се фклучени како линкови). Ова резултира во 7 дупликат атрибути кои се јавуваат во двата file-а (а тие атрибути се на assembly ниво / scope и можат да се јават најмногу еднаш). Во примерот кој се компајлира (Product.zip) file-овите со заеднички информации ги има **само еднаш**, и то се фклучени како **линкови** во **Properties** фолдерот.
Пред да се врати кодот во github **задолжително** е истиот да се компајлира без грешки, зато шо ко ќе друг член на тимот го земи последниот код, то ќе предизвика грешка во неговата околина. Во Microsoft Team Foundation Server постои нешто шо се вика gated check-in build: се дефинира дека кодот се билда пред секој check-in (commit) и ако билдот помини тогаш измените се прифатени, инаку програмерот не можи да го врати кодот во source control..

**Comment by andreaFIKT** [comment]
Popraveno.

**Comment by goce-smilevski** [comment]
Сега VersionInfo фајлот го нема (можно е да е изгубен при последните проблеми со кодот) и поради ова пак проектот не се компајлира :)
Во проектот имаме:

    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\ProductInfo.cs" />
    <Compile Include="Properties\VersionInfo.cs" />

шо значи дека сеуште се фклучени како нормални фајлови.

**Comment by andreaFIKT** [comment]
Sredeno e.

**Comment by goce-smilevski** [comment]
Case closed :)
