### ISSUE TITLE
Нова тура чистење во Domain проектот

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#6]
Конструкторите во Collection<T> класите не ги повикуваат наследените конструктори:
[(примери за конструктори)](https://csharp.2000things.com/tag/constructors/)

Станардизација на имиња на property-ја: или сите да се Id / Ime (како во Predmet, Oblast и сл.) или сите да се Id{Objekt} / Ime{Objekt} (како во Kompanija). Јас лично гласам за првата опција, зато шо секогаш ќе знајме за кој објект се однесува property-то, а подоцна можи и да воведиме основна класа и да ги стандардизираме овие property-ја.

PrijavaTehnologii го крши правилото за име на класа во еднина.

Tehnologija.Oblast: ако веќе имаме вакво проперти, подобро би било да е цел објект Oblast за да можиме да ги сместиме сите вредности. Она шо ќе ни треба појќе е Oblast.Tehnologii (примери за ова има во Product.zip со Parent. Children). Накратко, private read-only колекција која ќе ги содржи технологиите во рамки на одредена област.

Domain object model-от треба да е синхронизиран со структурата на базата на податоци и ова е процес шо ќе се одвива при секоја промена на database проектот.

Време е малце коментари да се напишат, накратко за секоја класа и секое проперти по збор-два шо претставува и шо му е намената [(примери)](https://msdn.microsoft.com/en-us/library/x4sa0ak0(v=vs.100).aspx)
После то не ќе е лошо да се проба и генерирање на документација ([еве како](http://www.codeproject.com/Articles/11082/C-and-XML-Source-Code-Documentation))
Екраните се за малце постара верзија на Visual Studio, ама опциите се тие. На крајот би требало да се добие help file со коментарите од кодот.

**Comment by lencetanaskoska** [comment]
Не сум сигурна дека точно ве сфатив околу делот Oblast.Tehnologii, остатокот мислам дека е во ред. Поздрав

**Comment by goce-smilevski** [comment]
Една Oblast можи да има појќе Tehnologija објекти (на пример област „Софтверско инженерство“ технологии ASP.NET, C#, Java, C++ итн.Или област Бази на податоци, технологии MS SQL Server, ORACLE, MySQL итн.)
Во Product.sln во Domain проектот има класи Parent и Child. Секој Parent има колекција Children. Односот меѓу Parent и Child е логички ист како односот меѓу Oblast и Tehnologija. Накратко, објектот-родител на повисоко ниво има колекција од објекти-деца на пониско ниво. Колекцијата е имплементирана како **приватна member-променлива** која се иницијализира во конструкторот,а пристапот до неа е решен преку **read-only property**.

**Comment by lencetanaskoska** [comment]
И документацијата за Domain е прикачена.
