### ISSUE TITLE
Database проектот е премногу вгнезден во фолдери

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#7]
Имаме Database\Database\Database.sqlproj. Ова најверојатно потекнува од то шо на почетокот проектот беше во посебен solution. Сега кога веќе е дел од официјалниот solution паметно е да е во фолдер на едно ниво погоре:
Database\Database.sqlproj
Не сум сигурен за github, ама за ова можи да треба 2 commit-и:
еден да се отстрани (Remove) Database.sqlproj од solution-от и да се премести во фолдерот погоре (на ниво на file system):
еден да се фклучи пофторно во solution-от. (Add existing project)

И кога веќе го асимилирафме проектот во LearnByPractice.sln, не ни треба појќе Database.sln како фајл. па можи да се бриши.

**Comment by lencetanaskoska** [comment]
Поправено
