### ISSUE TITLE
Тестови за Domain проектот

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#8]
Бидејќи моментално нема некоја тешка деловна логика во проектот, ќе тестираме очигледни работи, колку за загревање, да се види суштината на unit test-ирањето.
За почеток:
- за секоја класа за поединечен објект ќе тестираме дека после креирањето на нов објект, својствата му се иницијализирани на default вредностите (како на пример, int својства на нула, а стринг својства на null).
- за сеокја класа за колекција ќе тестираме дека е празна (т.е. дека Count е 0).

[Пример 1](http://www.codeproject.com/Articles/178635/Unit-Testing-Using-NUnit)
[Пример 2](http://www.4guysfromrolla.com/articles/011905-1.aspx#postadlink)

**Comment by lencetanaskoska** [comment]
Додадени тестовите :)

**Comment by goce-smilevski** [comment]
Одлично, со две мали забелешки:

1. изгледа Visual Studio не го додава афтоматски на github фолдерот packages, па ќе треба рачно да го додајш и commit-ираш. Ова е за да се избегни да мора да се прај рачно restore преку Niuget Package Manager, т.е. одма после fetch / pull на кодот, фолдерот да е спуштен во околината кај секој член на тимот.

2. Фтората работа е самиот NUnit. Референцата е додаена како од локалната околина. Кога се референцираат надворешни библиотеки паметно е истите да се ископирани во некој фолдер кој е во рамки на дрвото со solution-от или, сега по ново, со референцирање на Nuget package. Зато пробај прво да го додајш NUnit како package кон solution-от а после да го **референцираш nunit.framework.dll од package-от**.

Гледам дека сите останати NUnit референци во Tests проектот се попраја откако го спуштиф рачно (со restore) NUnit Test Adapter-от за Visual Studio (зато е првата забелешка, да се избегни овај чекор), а единствено оваја референца остана со извичник, како да фали.

**Comment by goce-smilevski** [comment]
Нема крај :)
Остана уште крајот на точка 2 (референцата да се смени да го зема длл-от од package-от.

**Comment by lencetanaskoska** [comment]
Мисла дека сега е во ред...

**Comment by goce-smilevski** [comment]
Апсолутно, се компајлира и сите тестој се зелени ... освен еден. Ама то произлегва од погрешен избор да тип на податок, па ќе отворам ново issue ... кое не мора да се решава денес, бидејќи сепак е недела :)
