### ISSUE TITLE
Енумерацијата за пол треба да има default вредност

### ISSUE THREAD

**Issue by goce-smilevski** [Kukunoska/LearnByPractice#9]
Обично ваквата вредност се вика None, ама ајде во нашиот случај нека е Nepoznat. То ќе биди default вредност за променливи од овај тип, т.е. кај шо има својства на објекти, ќе треба да се осигуриме дека после конструирањето на нов објект, соодветното својство ја има вредноста Pol.Nepoznat. **Ако ваквата логика не се применува по default** од страна на компајлерот и .NET, ќе треба во конструкторот да се додај една линија за доделување на вредноста.

**Comment by andreaFIKT** [comment]
Popraveno.

**Comment by goce-smilevski** [comment]
Зошто би воведувале енумерација ако после користиме стринг ?
Иако во базата полето е char, во домен моделот ќе е енумерација, а претворањето ќе го врши DAL проектот.
Ако има проблеми поради исто име на енумерацијата и својството, енумерацијата нека се вика PolEnum а својството само Pol.
На кодот добро ќе му дојди едно автоматско форматирање (Ctrl+K+D).

**Comment by andreaFIKT** [comment]
Sredeno.
